# 这是Mirai插件信息文件配置
# name: 你的插件名字
name: "DaceMiraiBot"
# author: 此插件的作者
author: "Dace"
# main: 你的主类名字, 需要继承 PluginBase
main: "com.dace.plugin.PluginMain"
# version: 插件版本
version: "1.1"
# info: 一句显示, 用处未知
info: "This is Dace's bot"